version: '3'
services:
  node-app:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=Nafis
      - MONGO_PASSWORD=garlic123
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Nafis  
      - MONGO_INITDB_ROOT_PASSWORD=garlic123
      